# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Qinjingxue.SunPack
PackageVersion: v1.0.0
MinimumOSVersion: 10.0.14393.0
InstallerType: inno
Scope: machine
ElevationRequirement: elevationRequired
UpgradeBehavior: install
ReleaseDate: 2026-10-03
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Qinjingxue/Sunpack/releases/download/v1.0.0/sunpack-windows-x64-v1.0.0-setup.exe
    InstallerSha256: A1095A9DEE43BC664E78E3FF5450D978758FD7EBDD59DBAD8F4A4A539C92FC93
    ProductCode: '{9E8C73E5-C540-4E68-93E0-1FBAAFB89713}_is1'
    AppsAndFeaturesEntries:
      - DisplayName: SunPack v1.0.0 (x64)
        Publisher: SunPack
        ProductCode: '{9E8C73E5-C540-4E68-93E0-1FBAAFB89713}_is1'
  - Architecture: arm64
    InstallerUrl: https://github.com/Qinjingxue/Sunpack/releases/download/v1.0.0/sunpack-windows-arm64-v1.0.0-setup.exe
    InstallerSha256: 5403D6B89616B156EF33BF23DD06363B39312819D3E20AC5CC5B42AC361644DB
    ProductCode: '{9E8C73E5-C540-4E68-93E0-1FBAAFB89713}_is1'
    AppsAndFeaturesEntries:
      - DisplayName: SunPack v1.0.0 (arm64)
        Publisher: SunPack
        ProductCode: '{9E8C73E5-C540-4E68-93E0-1FBAAFB89713}_is1'
ManifestType: installer
ManifestVersion: 1.12.0