from __future__ import annotations

import os

import pytest

from sunpack.core.analysis.volume_anchor import probe_volume_anchor_paths
from sunpack.core.contracts.filesystem import DirectorySnapshot, FileEntry
from sunpack.core.passwords.internal.store import PasswordStore
from sunpack.core.passwords.relation_prober import RelationsPasswordProber
from sunpack.pipeline.discovery.relations.scheduler import RelationsScheduler
from tests.helpers.real_archives import create_encrypted_rar_archive


# Real RAR 5.60 -hp fixtures (password "secret") generated by the bundled
# Rar.exe: a single volume plus the first two split volumes.
SINGLE_HP_HEX = (
    "526172211a07010074de7b1c21040000010f7b64253244702e2a32eb93579555a37d"
    "38b616cb97898c463d3682920551724ed0c1c974029cc2b8ef8491fc816311daa1b0"
    "410f6115608170466e4948a8c6d4f17e28b08c727b4acfc116d3d075ce011963dc0c"
    "72e50a803d9036619810e92352e809830c9463ab4a0abdaab61e008218673e9c5140"
    "9f76b2064bf7982e56d8173f1e387329bd5aca3bac49063545fcbfc19547d2be214b"
    "4fe1dae172b250e168f2a258548930b1763fb500c7869d70f2539d86fd19214dcc3b"
    "ca1363154b0a0f2b0bba7dcc224ec1893cbc31cfa95158ccf5e96d74921de6f268ea"
    "4429e2ddf63d49220005742fef059f868372345f071322a7e690d56d5ac17b563fa9"
    "e923076fa2c58aa8e88e9843df17b7e79a30ca936d8215c92f6832f86887c3c3160e"
    "cfddfcdf7712382f84f39eb8"
)
PART1_HP_HEX = (
    "526172211a070100ba274f7921040000010fb5b78bc874c2401abc24a83cef823460"
    "c50737df44187dc3fa3a8316028f5a16a7ec9cd527eff412f0bd4f8e579a17b4f089"
    "c86869ed79e1eda2749f3ec19c16fa0a126c255e5a0ade47c823d3c82ddc00c1c6ca"
    "ebf6506ef16dd177984ee975d3669ff26194eee05db61c51b12d618f31b63f8edfe5"
    "828ad2c512093459f242c0b23a51614fe315c307cbdac485"
)
PART2_HP_HEX = (
    "526172211a070100ba274f7921040000010fb5b78bc874c2401abc24a83cef823460"
    "c50737df44187dc3fa3a831619b05ee4bf8e2194083d002591665679b4863aed7850"
    "6ef5d174ab922c0c6c14e872055e0c440d2288a78fca53664503b46b93be4dc1f580"
    "98453bfc79bc498cb0cff26cdfadb5a13581c4bc1ae85166bbf4b013ccbd11873b02"
    "c45cbc42b8d64ca2effb581d24eddb503087a1cfb8599789"
)


def _write_hex(path, hex_value: str) -> str:
    path.write_bytes(bytes.fromhex(hex_value))
    return str(path)


def _snapshot(root, paths):
    entries = [
        FileEntry(path=os.path.join(root, name), is_dir=False, size=os.path.getsize(os.path.join(root, name)))
        for name in paths
    ]
    return DirectorySnapshot.from_entries(os.path.abspath(root), entries)


def test_probe_hp_single_volume_requires_and_accepts_password(tmp_path):
    path = _write_hex(tmp_path / "single.rar", SINGLE_HP_HEX)

    unresolved = probe_volume_anchor_paths([path])
    anchor = unresolved.get(path)
    assert anchor is not None
    assert anchor.format == "rar"
    assert anchor.confidence == "strong"
    assert anchor.encrypted is True
    assert anchor.needs_password is True
    assert anchor.wrong_password is False
    assert anchor.multivolume is False, "encrypted headers must not force multivolume"
    assert anchor.standalone is False

    wrong = probe_volume_anchor_paths([path], path_passwords={path: "nope"})
    assert wrong.get(path).wrong_password is True
    assert wrong.get(path).multivolume is False

    resolved = probe_volume_anchor_paths([path], path_passwords={path: "secret"})
    anchor = resolved.get(path)
    assert anchor.standalone is True
    assert anchor.multivolume is False
    assert anchor.needs_password is False


def test_probe_hp_split_volumes_use_decrypted_numbers(tmp_path):
    first = _write_hex(tmp_path / "vol.part1.rar", PART1_HP_HEX)
    second = _write_hex(tmp_path / "vol.part2.rar", PART2_HP_HEX)
    passwords = {first: "secret", second: "secret"}

    rows = probe_volume_anchor_paths([first, second], path_passwords=passwords)
    assert rows.get(first).multivolume is True
    assert rows.get(first).internal_volume_number == 1
    assert rows.get(first).anchor_roles == ("any_volume", "first")
    assert rows.get(second).multivolume is True
    assert rows.get(second).internal_volume_number == 2
    assert rows.get(second).anchor_roles == ("any_volume", "member")


def test_probe_rar4_hp_split_volumes_decrypts_following_headers(tmp_path):
    try:
        case = create_encrypted_rar_archive(
            tmp_path,
            "rar4_hp_split",
            password="secret",
            rar4=True,
            split=True,
            split_volume_size=1024,
            payload_size=8 * 1024,
        )
    except FileNotFoundError:
        pytest.skip("RAR generator is not configured")

    parts = sorted(str(path) for path in case.archive_dir.glob("*.rar"))
    assert len(parts) >= 2

    unresolved = probe_volume_anchor_paths(parts[:2])
    assert all(unresolved.get(path).encrypted for path in parts[:2])
    assert all(unresolved.get(path).needs_password for path in parts[:2])

    resolved = probe_volume_anchor_paths(
        parts[:2], path_passwords={path: "secret" for path in parts[:2]}
    )
    first, second = (resolved.get(path) for path in parts[:2])
    assert first.multivolume is True
    assert first.internal_volume_number == 1
    assert second.multivolume is True
    assert second.internal_volume_number is None
    assert all("rar4:decrypted_header" in row.evidence for row in (first, second))


def test_single_hp_rar_is_a_plain_file_group_not_a_split(tmp_path):
    _write_hex(tmp_path / "single.rar", SINGLE_HP_HEX)
    snapshot = _snapshot(tmp_path, ["single.rar"])
    groups = RelationsScheduler().build_candidate_groups(snapshot)
    assert len(groups) == 1
    group = groups[0]
    assert group.kind == "file"
    assert group.is_split_candidate is False


def test_single_hp_rar_with_split_like_filename_remains_a_plain_file_group(tmp_path):
    _write_hex(tmp_path / "single.part1.rar", SINGLE_HP_HEX)
    snapshot = _snapshot(tmp_path, ["single.part1.rar"])

    groups = RelationsScheduler().build_candidate_groups(snapshot)

    assert len(groups) == 1
    assert groups[0].kind == "file"
    assert groups[0].is_split_candidate is False


def test_two_standalone_hp_rars_in_same_filename_family_return_to_plain_files(tmp_path):
    _write_hex(tmp_path / "same.part1.rar", SINGLE_HP_HEX)
    _write_hex(tmp_path / "same.part2.rar", SINGLE_HP_HEX)
    snapshot = _snapshot(tmp_path, ["same.part1.rar", "same.part2.rar"])

    groups = RelationsScheduler({"user_passwords": ["secret"]}).build_candidate_groups(snapshot)

    assert {os.path.basename(group.head_path) for group in groups} == {
        "same.part1.rar",
        "same.part2.rar",
    }
    assert all(group.kind == "file" and not group.is_split_candidate for group in groups)


def test_missing_middle_hp_rar_volume_never_validates_as_complete_split(tmp_path):
    try:
        case = create_encrypted_rar_archive(
            tmp_path,
            "rar5_hp_missing_middle",
            password="secret",
            split=True,
            split_volume_size=1024,
            payload_size=12 * 1024,
        )
    except FileNotFoundError:
        pytest.skip("RAR generator is not configured")

    scheduler = RelationsScheduler({"user_passwords": ["secret"]})
    numbered = sorted(
        (
            path,
            scheduler.parse_numbered_volume(str(path)),
        )
        for path in case.archive_dir.iterdir()
        if path.is_file()
    )
    numbered = [item for item in numbered if item[1] is not None]
    numbered.sort(key=lambda item: int(item[1]["number"]))
    assert len(numbered) >= 3
    numbers = [int(parsed["number"]) for _path, parsed in numbered]
    assert numbers[0] == 1
    middle = next(path for path, parsed in numbered if int(parsed["number"]) == 2)
    hidden = middle.with_name(f"{middle.name}.hidden")
    middle.rename(hidden)
    try:
        remaining = [path.name for path, _parsed in numbered if path != middle]
        incomplete_paths = [case.archive_dir / name for name in remaining]
        incomplete = scheduler.build_candidate_groups(
            _snapshot(case.archive_dir, remaining),
            path_passwords={str(path): "secret" for path in incomplete_paths},
        )
        assert not any(group.kind == "split_archive" for group in incomplete)
    finally:
        hidden.rename(middle)

    complete_paths = [path for path, _parsed in numbered]
    complete = scheduler.build_candidate_groups(
        _snapshot(case.archive_dir, [path.name for path in complete_paths]),
        path_passwords={str(path): "secret" for path in complete_paths},
    )
    split_groups = [group for group in complete if group.kind == "split_archive"]
    assert len(split_groups) == 1
    assert [volume.number for volume in split_groups[0].split_volumes] == numbers


def test_split_hp_rar_group_is_identified_from_filenames(tmp_path):
    _write_hex(tmp_path / "vol.part1.rar", PART1_HP_HEX)
    _write_hex(tmp_path / "vol.part2.rar", PART2_HP_HEX)
    snapshot = _snapshot(tmp_path, ["vol.part1.rar", "vol.part2.rar"])
    groups = RelationsScheduler().build_candidate_groups(snapshot)
    split_groups = [group for group in groups if group.kind == "split_archive"]
    assert len(split_groups) == 1
    assert [volume.number for volume in split_groups[0].split_volumes] == [1, 2]


def test_split_hp_rar_group_accepts_camouflage_around_contiguous_part_token(tmp_path):
    first_name = "文件名.伪装名.伪装名part1伪装名.伪装名"
    second_name = "文件名.伪装名.伪装名part2伪装名.伪装名"
    _write_hex(tmp_path / first_name, PART1_HP_HEX)
    _write_hex(tmp_path / second_name, PART2_HP_HEX)
    snapshot = _snapshot(tmp_path, [first_name, second_name])

    groups = RelationsScheduler().build_candidate_groups(snapshot)
    split_group = next(group for group in groups if group.kind == "split_archive")

    assert [volume.number for volume in split_group.split_volumes] == [1, 2]
    assert {os.path.basename(path) for path in split_group.input_paths} == {
        first_name,
        second_name,
    }


def test_relations_password_prober_remembers_success_and_skips_second_probe(tmp_path):
    first = _write_hex(tmp_path / "vol.part1.rar", PART1_HP_HEX)
    _write_hex(tmp_path / "vol.part2.rar", PART2_HP_HEX)
    snapshot = _snapshot(tmp_path, ["vol.part1.rar", "vol.part2.rar"])
    groups = RelationsScheduler().build_candidate_groups(snapshot)
    group = next(group for group in groups if group.kind == "split_archive")

    store = PasswordStore.from_sources(
        cli_passwords=["secret"],
        builtin_passwords=[],
    )
    prober = RelationsPasswordProber(store)
    calls = {"count": 0}
    original_verify = prober.scheduler.verifier.verify_fast_batch

    def counting_verify(archive_path, passwords, **kwargs):
        calls["count"] += 1
        return original_verify(archive_path, passwords, **kwargs)

    prober.scheduler.verifier.verify_fast_batch = counting_verify
    assert prober.resolve_file(group.head_path) == "secret"
    assert calls["count"] == 1
    assert store.recent_passwords == ["secret"]

    # The second probe hits the PasswordAttemptCache without touching the
    # fast verifier again (same bytes, same fingerprint).
    assert prober.resolve_file(group.head_path) == "secret"
    assert calls["count"] == 1


def test_relations_password_prober_returns_none_without_candidates(tmp_path):
    first = _write_hex(tmp_path / "vol.part1.rar", PART1_HP_HEX)
    _write_hex(tmp_path / "vol.part2.rar", PART2_HP_HEX)
    snapshot = _snapshot(tmp_path, ["vol.part1.rar", "vol.part2.rar"])
    group = next(
        group
        for group in RelationsScheduler().build_candidate_groups(snapshot)
        if group.kind == "split_archive"
    )
    prober = RelationsPasswordProber(PasswordStore.from_sources())
    assert prober.resolve_file(group.head_path) is None
