from __future__ import annotations

import os

import pytest

from sunpack.core.contracts.filesystem import DirectorySnapshot, FileEntry
from sunpack.core.passwords.internal.store import PasswordStore
from sunpack.core.passwords.relation_prober import RelationsPasswordProber
from sunpack.pipeline.discovery.relations.scheduler import RelationsScheduler
from tests.helpers.real_archives import ArchiveFixtureFactory, create_encrypted_rar_archive
from tests.helpers.fs_builder import make_minimal_pe


# Real RAR 5.60 -hp fixtures (password "secret") generated by the bundled
# Rar.exe: a single volume plus the first two split volumes.
SINGLE_HP_HEX = (
    "526172211a07010074de7b1c21040000010f7b64253244702e2a32eb93579555a37d"
    "38b616cb97898c463d3682920551724ed0c1c974029cc2b8ef8491fc816311daa1b0"
    "410f6115608170466e4948a8c6d4f17e28b08c727b4acfc116d3d075ce011963dc0c"
    "72e50a803d9036619810e92352e809830c9463ab4a0abdaab61e008218673e9c5140"
    "9f76b2064bf7982e56d8173f1e387329bd5aca3bac49063545fcbfc19547d2be214b"
    "4fe1dae172b250e168f2a258548930b1763fb500c7869d70f2539d86fd19214dcc3b"
    "ca1363154b0a0f2b0bba7dcc224ec1893cbc31cfa95158ccf5e96d74921de6f268ea"
    "4429e2ddf63d49220005742fef059f868372345f071322a7e690d56d5ac17b563fa9"
    "e923076fa2c58aa8e88e9843df17b7e79a30ca936d8215c92f6832f86887c3c3160e"
    "cfddfcdf7712382f84f39eb8"
)
PART1_HP_HEX = (
    "526172211a070100ba274f7921040000010fb5b78bc874c2401abc24a83cef823460"
    "c50737df44187dc3fa3a8316028f5a16a7ec9cd527eff412f0bd4f8e579a17b4f089"
    "c86869ed79e1eda2749f3ec19c16fa0a126c255e5a0ade47c823d3c82ddc00c1c6ca"
    "ebf6506ef16dd177984ee975d3669ff26194eee05db61c51b12d618f31b63f8edfe5"
    "828ad2c512093459f242c0b23a51614fe315c307cbdac485"
)
PART2_HP_HEX = (
    "526172211a070100ba274f7921040000010fb5b78bc874c2401abc24a83cef823460"
    "c50737df44187dc3fa3a831619b05ee4bf8e2194083d002591665679b4863aed7850"
    "6ef5d174ab922c0c6c14e872055e0c440d2288a78fca53664503b46b93be4dc1f580"
    "98453bfc79bc498cb0cff26cdfadb5a13581c4bc1ae85166bbf4b013ccbd11873b02"
    "c45cbc42b8d64ca2effb581d24eddb503087a1cfb8599789"
)


def _write_hex(path, hex_value: str) -> str:
    path.write_bytes(bytes.fromhex(hex_value))
    return str(path)


def _snapshot(root, paths):
    entries = [
        FileEntry(path=os.path.join(root, name), is_dir=False, size=os.path.getsize(os.path.join(root, name)))
        for name in paths
    ]
    return DirectorySnapshot.from_entries(os.path.abspath(root), entries)


@pytest.mark.parametrize("pe_offset", [0x80, 0x800])
@pytest.mark.parametrize("split", [False, True])
def test_encrypted_sfx_retry_preserves_confirmed_pe_facts(tmp_path, pe_offset, split):
    from sunpack.pipeline.coordinator.target_scan import build_native_table_for_targets
    from sunpack.pipeline.discovery.filesystem.directory_scanner import DirectoryScanner
    from tests.helpers.config_factory import make_config

    first = tmp_path / ("payload.part1.jpg" if split else "payload.jpg")
    image = make_minimal_pe(b"WinRAR SFX", pe_offset=pe_offset)
    first.write_bytes(image + bytes.fromhex(PART1_HP_HEX if split else SINGLE_HP_HEX))
    if split:
        _write_hex(tmp_path / "payload.part2.bin", PART2_HP_HEX)
    config = make_config()
    snapshot = DirectoryScanner(str(tmp_path), config=config).scan()
    table = build_native_table_for_targets([str(first)], config=config)
    passwords = [(str(first), "secret")]
    if split:
        passwords.append((str(tmp_path / "payload.part2.bin"), "secret"))
    table.retry_relations(snapshot.raw_native_snapshot, snapshot.native_snapshot, passwords)
    assert len(table) == 1
    kind, group = table.project(0)
    assert kind == "relation"
    metadata = group["head_metadata"]
    assert metadata["sfx"] is True
    assert metadata["pe_structure"] is True
    assert metadata["structure_offset"] == len(image)
    assert metadata["needs_password"] is False


@pytest.mark.parametrize("name", ["single.rar", "single.part1.rar"])
def test_single_hp_rar_with_split_like_filename_remains_a_plain_file_group(tmp_path, name):
    _write_hex(tmp_path / name, SINGLE_HP_HEX)
    snapshot = _snapshot(tmp_path, [name])

    groups = RelationsScheduler().build_candidate_groups(snapshot)

    assert len(groups) == 1
    assert groups[0].kind == "file"
    assert groups[0].is_split_candidate is False


def test_two_standalone_hp_rars_in_same_filename_family_return_to_plain_files(tmp_path):
    _write_hex(tmp_path / "same.part1.rar", SINGLE_HP_HEX)
    _write_hex(tmp_path / "same.part2.rar", SINGLE_HP_HEX)
    snapshot = _snapshot(tmp_path, ["same.part1.rar", "same.part2.rar"])

    groups = RelationsScheduler({"user_passwords": ["secret"]}).build_candidate_groups(snapshot)

    assert {os.path.basename(group.head_path) for group in groups} == {
        "same.part1.rar",
        "same.part2.rar",
    }
    assert all(group.kind == "file" and not group.is_split_candidate for group in groups)


def test_password_retry_keeps_unencrypted_structure_facts_native(tmp_path, monkeypatch):
    rar_path = _write_hex(tmp_path / "encrypted.rar", SINGLE_HP_HEX)
    case = ArchiveFixtureFactory().create(
        tmp_path / "fixtures", "plain", "zip", split=True,
        payload_size=8 * 1024, split_volume_size=1024,
    )
    parts = [path.replace(tmp_path / path.name) for path in sorted(case.archive_dir.iterdir())]
    assert len(parts) > 1
    snapshot = _snapshot(tmp_path, ["encrypted.rar", *[path.name for path in parts]])
    scheduler = RelationsScheduler()

    def discover(encrypted_groups):
        # Only password-blocked data crosses Python before the final projection.
        assert len(encrypted_groups) == 1
        assert encrypted_groups[0].head_path == rar_path
        for path in parts:
            path.unlink()
        return {rar_path: "secret"}

    monkeypatch.setattr(scheduler._builder, "_discover_directory_passwords", discover)
    groups = scheduler.build_candidate_groups(snapshot)
    zip_group = next(group for group in groups if group.head_metadata.get("format") == "zip")
    assert zip_group.head_metadata["relation_confirmed"] is True
    assert zip_group.head_metadata.get("volume_set_incomplete") is not True
    assert zip_group.input_paths == [str(path) for path in parts]
    rar_group = next(group for group in groups if group.head_path == rar_path)
    assert rar_group.kind == "file"
    assert rar_group.head_metadata["needs_password"] is False


def test_missing_middle_hp_rar_volume_never_validates_as_complete_split(tmp_path):
    try:
        case = create_encrypted_rar_archive(
            tmp_path,
            "rar5_hp_missing_middle",
            password="secret",
            split=True,
            split_volume_size=1024,
            payload_size=12 * 1024,
        )
    except FileNotFoundError:
        pytest.skip("RAR generator is not configured")

    scheduler = RelationsScheduler({"user_passwords": ["secret"]})
    numbered = sorted(
        (
            path,
            scheduler.parse_numbered_volume(str(path)),
        )
        for path in case.archive_dir.iterdir()
        if path.is_file()
    )
    numbered = [item for item in numbered if item[1] is not None]
    numbered.sort(key=lambda item: int(item[1]["number"]))
    assert len(numbered) >= 3
    numbers = [int(parsed["number"]) for _path, parsed in numbered]
    assert numbers[0] == 1
    middle = next(path for path, parsed in numbered if int(parsed["number"]) == 2)
    hidden = middle.with_name(f"{middle.name}.hidden")
    middle.rename(hidden)
    try:
        remaining = [path.name for path, _parsed in numbered if path != middle]
        incomplete_paths = [case.archive_dir / name for name in remaining]
        incomplete = scheduler.build_candidate_groups(
            _snapshot(case.archive_dir, remaining),
            path_passwords={str(path): "secret" for path in incomplete_paths},
        )
        # A gapped set is never a complete relation; it is handed to
        # Extraction as an explicitly incomplete set so the worker reports
        # the missing volume instead of the set vanishing from discovery.
        split_groups = [group for group in incomplete if group.is_split_candidate]
        assert split_groups
        assert all(
            group.head_metadata.get("volume_set_incomplete") is True
            for group in split_groups
        )
    finally:
        hidden.rename(middle)

    complete_paths = [path for path, _parsed in numbered]
    complete = scheduler.build_candidate_groups(
        _snapshot(case.archive_dir, [path.name for path in complete_paths]),
        path_passwords={str(path): "secret" for path in complete_paths},
    )
    split_groups = [group for group in complete if group.kind == "split_archive"]
    assert len(split_groups) == 1
    assert [volume.number for volume in split_groups[0].split_volumes] == numbers


@pytest.mark.parametrize("pattern", ["vol.part{}.rar", "文件名.伪装名.伪装名part{}伪装名.伪装名"])
def test_split_hp_rar_group_accepts_camouflage_around_contiguous_part_token(tmp_path, pattern):
    first_name, second_name = pattern.format(1), pattern.format(2)
    _write_hex(tmp_path / first_name, PART1_HP_HEX)
    _write_hex(tmp_path / second_name, PART2_HP_HEX)
    snapshot = _snapshot(tmp_path, [first_name, second_name])

    groups = RelationsScheduler().build_candidate_groups(snapshot)
    split_group = next(group for group in groups if group.kind == "split_archive")

    assert [volume.number for volume in split_group.split_volumes] == [1, 2]
    assert {os.path.basename(path) for path in split_group.input_paths} == {
        first_name,
        second_name,
    }


def test_encrypted_unresolved_members_all_receive_the_discovered_password(tmp_path):
    names = ["shared.alpha.foo", "shared.beta.bar"]
    paths = [
        _write_hex(tmp_path / names[0], PART1_HP_HEX),
        _write_hex(tmp_path / names[1], PART2_HP_HEX),
    ]
    snapshot = _snapshot(tmp_path, names)
    unresolved = RelationsScheduler().build_candidate_groups(snapshot)
    assert len(unresolved) == 1
    assert set(unresolved[0].input_paths) == set(paths)
    assert unresolved[0].split_volumes == []
    assert unresolved[0].head_metadata["relation_confirmed"] is False
    assert unresolved[0].head_metadata["needs_password"] is True
    resolved = RelationsScheduler({"user_passwords": ["secret"]}).build_candidate_groups(snapshot)
    assert len(resolved) == 1
    assert [part.number for part in resolved[0].split_volumes] == [1, 2]
    assert set(resolved[0].input_paths) == set(paths)
    assert resolved[0].head_metadata["needs_password"] is False


def test_relations_password_prober_remembers_success_and_skips_second_probe(tmp_path):
    _write_hex(tmp_path / "vol.part1.rar", PART1_HP_HEX)
    _write_hex(tmp_path / "vol.part2.rar", PART2_HP_HEX)
    snapshot = _snapshot(tmp_path, ["vol.part1.rar", "vol.part2.rar"])
    groups = RelationsScheduler().build_candidate_groups(snapshot)
    group = next(group for group in groups if group.kind == "split_archive")

    assert RelationsPasswordProber(PasswordStore.from_sources()).resolve_file(group.head_path) is None
    store = PasswordStore.from_sources(
        cli_passwords=["secret"],
        builtin_passwords=[],
    )
    prober = RelationsPasswordProber(store)
    calls = {"count": 0}
    original_verify = prober.scheduler.verifier.verify_fast_batch

    def counting_verify(archive_path, passwords, **kwargs):
        calls["count"] += 1
        return original_verify(archive_path, passwords, **kwargs)

    prober.scheduler.verifier.verify_fast_batch = counting_verify
    assert prober.resolve_file(group.head_path) == "secret"
    assert calls["count"] == 1
    assert store.recent_passwords == ["secret"]

    # The second probe hits the PasswordAttemptCache without touching the
    # fast verifier again (same bytes, same fingerprint).
    assert prober.resolve_file(group.head_path) == "secret"
    assert calls["count"] == 1
